### ISSUE TITLE
Identify candidate land cover datasets

### ISSUE THREAD

**Issue by mojodna** [mojodna/marblecutter#102]
* **NLCD 2011** for the USA
  * **link:** https://www.mrlc.gov/nlcd2011.php
  * **legend:** https://www.mrlc.gov/nlcd11_leg.php
  * **resolution:** 30 meter
  * **schema:** 8 classes (including water)
    * 16 sub classes (there are 4 more, though, for Alaska)
   * > As with two previous NLCD land cover products NLCD 2011 keeps the same **16-class** land cover classification scheme that has been applied consistently across the United States at a spatial resolution of **30 meters**. NLCD 2011 is based primarily on a decision-tree classification of circa 2011 Landsat satellite data. 
* **NLCD 2016** for the USA
  https://www.mrlc.gov/2018/
  planned release Friday, December 28, 2018, as an update to same formats and distributions as 2011 version.
  > Incorporation of new shrub and grass mapping in the Western U.S. is being completed. This will provide separate fractional vegetation products for download, and also be incorporated into the land cover for improved accuracy
* **Climate Change Initiative (CCI) Land Cover V2**
  * **300 meter** global with **23 classes**, probably better in Europe, in Africa 20 meters
  * http://maps.elie.ucl.ac.be/CCI/viewer/index.php
  * https://www.esa-landcover-cci.org/
  * http://maps.elie.ucl.ac.be/CCI/viewer/download/CCI-LC_Maps_Legend.pdf
* **Global Land Survey (GLS)**
  * **30 meter** global but just tree canopy %
* MCD12Q1 0.5 km MODIS-based Global Land Cover Climatology
  * **500-meter** MODIS Land Cover Maps with **17 classes** but over 10 year span
  * https://landcover.usgs.gov/global_climatology.php
* **Corine Land Cover** in Europe
  * 100 meters
  * https://land.copernicus.eu/pan-european/corine-land-cover/clc-2012?tab=metadata

See also:

- https://gisgeography.com/free-global-land-cover-land-use-data/

**Comment by mojodna** [comment]
s3://land-cover-sources/mirror/ currently contains mirrors of:

* MODIS (2012.01.01)
* NLCD CONUS (2011)
* NLCD AK (2011)
* NLCD HI (2010-2011, dates vary by island)
* NLCD PR, USVI, CNMI, AS (dates vary by island)

All NLCD sources are in Erdas Imagine format. MODIS is in gzipped GeoTIFF tiles (MODIS, not Web Mercator).

**Comment by nvkelso** [comment]
* **Older MODIS Global Land Cover**
    - 1 km with older date
    - https://visibleearth.nasa.gov/view.php?id=61004

**Comment by nvkelso** [comment]
Added the Europe data from Corine in https://github.com/mojodna/marblecutter/issues/102#issue-355358438.

**Comment by mojodna** [comment]
20m source for Africa (referenced above): http://2016africalandcover20m.esrin.esa.int/

**Comment by mojodna** [comment]
In practice, MCD12Q1 0.5 km MODIS-based Global Land Cover Climatology ("MODIS") isn't used at the moment, as Climate Change Initiative (CCI) Land Cover V2 ("ESACCI-LC") has greater coverage and higher resolution.
