### ISSUE TITLE
Identify land cover classifications

### ISSUE THREAD

**Issue by mojodna** [mojodna/marblecutter#103]
Somewhere between 8-16 core types, optional sub-types.

**Comment by nvkelso** [comment]
Riffing off the USGS's NLCD [landcover legend](https://www.mrlc.gov/nlcd11_leg.php):

1. **water** 
    - Maps to OSM **water**, sea, ocean, riverbank, reservoir tags, and **glacier**
    - **kind_detail**:
        1. Open Water
        1. Perennial Ice/Snow
1. **developed**
    - Maps to OSM implied **urban** tags (residential, industrial, various admin), and Natural Earth's **urban_area**
      - **kind_detail**:
        1. Developed, Low Intensity
        1. Developed, Medium Intensity
        1. Developed High Intensity
1. **barren** (catchall for Rock/Sand/Clay)
    - Maps to OSM natural=**rock**, natural=sand, surface=* & etc tags
1. **forest**
    - Maps to OSM **forest** and wood tags, with kind_detail relating to OSM's leaf_type=[broadleaved, needleleaved, mixed]  and OSM's leaf_cycle=[deciduous, evergreen, mixed].
    - **kind_detail**:
        1. Deciduous Forest
        1. Evergreen Forest
        1. Mixed Forest
1. **shrubland**
    - Maps to OSM natural=**scrub** tag
    - **kind_detail**:
        1. Shrub/Scrub
        1. alaska only Dwarf Scrub
1. **herbaceous**
    - Maps to OSM landcover=**grass** tag
    - **kind_detail**:
        1. Grassland/Herbaceous
        1. alaska Sedge/Herbaceous
        1. alaska Lichens
        1. alaska Moss
1. **cultivated**
    - Maps to OSM **farm**, farmland, crops, agriculture related tags
    - **kind_detail**:
        1. Pasture/Hay
        1. Cultivated Crops
1. **wetlands**
    - Maps to OSM natural=**wetland** related tags
    - **kind_detail**:
        1. Woody Wetlands
        2. Emergent Herbaceous Wetlands

**Comment by nvkelso** [comment]
Legend of the global **CCI‐LC** maps, based on LCCS mapped to the 8 top level kind values from USGS NLCD:

1. **water** 
    * 210 Water bodies
    * 220 Permanent snow and ice
1. **developed**
    * 190 Urban areas
1. **barren** (catchall for Rock/Sand/Clay)
    * 200 Bare areas
    * 201 Consolidated bare areas
    * 202 Unconsolidated bare areas
1. **forest**
    * 40 Mosaic natural vegetation (tree, shrub, herbaceous cover) (>50%) / cropland (<50%)  
    * 50 Tree cover, broadleaved, evergreen, closed to open (>15%)
    * 60 Tree cover, broadleaved, deciduous, closed to open (>15%)
    * 61 Tree cover, broadleaved, deciduous, closed (>40%)
    * 62 Tree cover, broadleaved, deciduous, open (15‐40%)
    * 70 Tree cover, needleleaved, evergreen, closed to open (>15%)
    * 71 Tree cover, needleleaved, evergreen, closed (>40%)
    * 72 Tree cover, needleleaved, evergreen, open (15‐40%)
    * 80 Tree cover, needleleaved, deciduous, closed to open (>15%)
    * 81 Tree cover, needleleaved, deciduous, closed (>40%)
    * 82 Tree cover, needleleaved, deciduous, open (15‐40%)
    * 90 Tree cover, mixed leaf type (broadleaved and needleleaved)
1. **shrubland**
    * 12 Tree or shrub cover
    * 100 Mosaic tree and shrub (>50%) / herbaceous cover (<50%)
    * 120 Shrubland
    * 121 Evergreen shrubland
    * 122 Deciduous shrubland
    * 150 Sparse vegetation (tree, shrub, herbaceous cover) (<15%)
    * 151 Sparse tree (<15%)
    * 152 Sparse shrub (<15%)
1. **herbaceous**
    * 11 Herbaceous cover
    * 110 Mosaic herbaceous cover (>50%) / tree and shrub (<50%)
    * 130 Grassland
    * 140 Lichens and mosses
    * 153 Sparse herbaceous cover (<15%)
1. **cultivated**
    * 10 Cropland, rainfed
    * 20 Cropland, irrigated or post‐flooding
    * 30 Mosaic cropland (>50%) / natural vegetation (tree, shrub, herbaceous cover) (<50%)
1. **wetlands**
    * 160 Tree cover, flooded, fresh or brakish water
    * 170 Tree cover, flooded, saline water
    * 180 Shrub or herbaceous cover, flooded, fresh/saline/brakish water
1. **other**
    * 0 No Data

**Comment by nvkelso** [comment]
**Corine Land Cover classes** (Europe) mapped to the 8 top level kind values from USGS NLCD:

https://land.copernicus.eu/user-corner/technical-library/Nomenclature.pdf

1. Artificial surfaces
    * 1.1. Urban fabric
        * 1.1.1. Continuous urban fabric
        * 1.1.2. Discontinuous urban fabric
    * 1.2. Industrial, commercial and transport units
        * 1.2.1. Industrial and commercial units
        1.2.2. Road and rail networks and associated land
        1.2.3. Port areas
        1.2.4. Airports
    * 1.3. Mine, dump and construction sites
        * 1.3.1. Mineral extraction sites
        * 1.3.2. Dump sites
        * 1.3.3. Construction sites
    * 1.4. Artificial non-agricultural vegetated areas
        * 1.4.1. Green urban areas
        * 1.4.2. Sport and leisure facilities

1. Agricultural areas
    * 2.1. Arable land
        * .1.1. Non-irrigated arable land
        * 2.1.2. Permanently irrigated land
        * 2.1.3. Rice fields
    * 2.2. Permanent crops
        * 2.2.1. Vineyards
        * 2.2.2. Fruit trees and berry plantations
        * 2.2.3. Olive groves
    * 2.3. Pastures
        * 2.3.1. Pastures
    * 2.4. Heterogeneous agricultural areas
        * 2.4.1. Annual crops associated with permanent crops
        * 2.4.2. Complex cultivation patterns
        * 2.4.3. Land principally occupied by agriculture, with significant areas of natural vegetation
        * 2.4.4. Agro-forestry areas

3. Forests and semi-natural areas
    * 3.1. Forests
        * 3.1.1. Broad-leaved forest
        * 3.1.2. Coniferous forest
        * 3.1.3. Mixed forest
    * 3.2. Shrub and/or herbaceous vegetation association
        * 3.2.1. Natural grassland
        * 3.2.2. Moors and heathland
        * 3.2.3. Sclerophyllous vegetation
        * 3.2.4. Transitional woodland shrub
    * 3.3. Open spaces with little or no vegetation
        * 3.3.1. Beaches, dunes, and sand plains
        * 3.3.2. Bare rock
        * 3.3.3. Sparsely vegetated areas
        * 3.3.4. Burnt areas
        * 3.3.5. Glaciers and perpetual snow

4. Wetlands
    * 4.1. Inland wetlands
        * 4.1.1. Inland marshes
        * 4.1.2. Peatbogs
    * 4.2. Coastal wetlands
        * 4.2.1. Salt marshes
        * 4.2.2. Salines
        * 4.2.3. Intertidal flats

5. Water bodies
    * 5.1. Inland waters
        * 5.1.1. Water courses
        * 5.1.2. Water bodies
    * 5.2. Marine waters
        * * 5.2.1. Coastal lagoons
        * 5.2.2. Estuaries
        * 5.2.3. Sea and ocean

**Comment by mojodna** [comment]
For NLCD, should this also be classified as **developed**, or should it be dropped / classified differently?

> Developed, Open Space- areas with a mixture of some constructed materials, but mostly vegetation in the form of lawn grasses. Impervious surfaces account for less than 20% of total cover. These areas most commonly include large-lot single-family housing units, parks, golf courses, and vegetation planted in developed settings for recreation, erosion control, or aesthetic purposes.

**Comment by mojodna** [comment]
The CCI-LC legend is here (and is simpler than the CORINE land cover nomenclature): https://maps.elie.ucl.ac.be/CCI/viewer/download/CCI-LC_Maps_Legend.pdf

I should have enough info to map this.

**Comment by mojodna** [comment]
`40` - "Mosaic natural vegetation (tree, shrub, herbaceous cover) (>50%) / cropland (<50%)" - thoughts? **cultivated**?
`150-153` - "sparse" - **barren**?

**Comment by mojodna** [comment]
```python
# NLCD
# https://www.mrlc.gov/nlcd11_leg.php
colormap = {
    11: water,
    12: water,
    21: developed,
    22: developed,
    23: developed,
    24: developed,
    31: barren,
    41: forest,
    42: forest,
    43: forest,
    51: shrubland,
    52: shrubland,
    71: herbaceous,
    72: herbaceous,
    73: herbaceous,
    74: herbaceous,
    81: cultivated,
    82: cultivated,
    90: wetlands,
    95: wetlands,
}

# ESACCI-LC
# https://maps.elie.ucl.ac.be/CCI/viewer/download/CCI-LC_Maps_Legend.pdf
colormap = {
    10: cultivated,
    11: cultivated,
    12: cultivated,
    20: cultivated,
    30: cultivated,
    40: cultivated,
    50: forest,
    60: forest,
    70: forest,
    71: forest,
    72: forest,
    80: forest,
    81: forest,
    82: forest,
    90: forest,
    100: shrubland,
    110: herbaceous,
    120: shrubland,
    121: shrubland,
    122: shrubland,
    130: herbaceous,
    140: herbaceous,
    150: barren,
    151: barren,
    152: barren,
    153: barren,
    160: wetlands,
    170: wetlands,
    180: wetlands,
    190: developed,
    200: barren,
    201: barren,
    202: barren,
    210: water,
    220: water,
}
```

**Comment by mojodna** [comment]
NLCD + ESACCI-LC, native colormaps:

![image](https://user-images.githubusercontent.com/45/45909079-cdd74400-bdb4-11e8-90c4-b04ebf48a4d5.png)


NLCD + ESACCI-LC, unified:

![image](https://user-images.githubusercontent.com/45/45909053-abddc180-bdb4-11e8-9fc5-0186bedcff0f.png)

**Comment by mojodna** [comment]
MODIS, native:

![image](https://user-images.githubusercontent.com/45/45909113-f7906b00-bdb4-11e8-8f8a-ddfc9f94d072.png)

MODIS, mapped:

![image](https://user-images.githubusercontent.com/45/45909139-0e36c200-bdb5-11e8-9bc8-3001bace4601.png)

**Comment by nvkelso** [comment]
Wow, these are looking great!

The thing I do like about MODIS is it's more appropriately generalized for lower zooms without needing as much processing to get there. So please keep it in the mix.

**Comment by mojodna** [comment]
Definitely. It's been good for uncovering some edge cases as well.

Another downside of MODIS is that it requires loading data from more files for lower zooms (where ESACCI-LC is a single, much larger file).

**Comment by mojodna** [comment]
Mappings documented here: https://github.com/mojodna/marblecutter-land-cover/blob/master/README.md#classification-correlation

If/when they change, the catalog metadata needs to be updated, e.g.

``sql
update land_cover set recipes='{"colormap": {"0": 10, "1": 40, "2": 40, "3": 40, "4": 40, "5": 40, "6": 50, "7": 50, "8": 70, "9": 70, "10": 70, "11": 90, "12": 80, "13": 20, "14": 80, "15": 10, "16": 30, "254": 0, "255": 0}}' where source='MODIS';
```

**Comment by mojodna** [comment]
C-CAP classifications, to be mapped:

```xml
      <attr>
        <attrlabl>Value</attrlabl>
        <attrdef>Landcover Classification as determined by NOAA Coastal Change Analysis Program (C-CAP)</attrdef>
        <attrdefs>NOAA Office for Coastal Management High-Resolution Land Cover Project</attrdefs>
        <attrdomv>
          <edom>
            <edomv>1 Unclassified</edomv>
            <edomvd>
This class contains no
data due to cloud conditions or data voids.
</edomvd>
            <edomvds>N/A</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>2 Impervious Surfaces</edomv>
            <edomvd>Anthropogenic features such as buildings, parking lots and roads developed from asphalt, concrete or other constructed surfaces which do not allow infiltration from precipitation.</edomvd>
            <edomvds>NOAA Office for Coastal Management High-Resolution Land Cover Project.</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>5 Open Spaces Developed</edomv>
            <edomvd>Includes areas with a mixture of some constructed materials, but mostly
vegetation in the form of lawn grasses. Impervious surfaces account for
less than 20 percent of total cover. These areas most commonly include
large-lot single-family housing units, parks, golf courses, and vegetation
planted in developed settings for recreation, erosion control, or
aesthetic purposes.</edomvd>
            <edomvds>
NLCD 2001 Land Cover Class Definitions, 2004
http://www.mrlc.gov/nlcd_definitions.asp
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>6 Cultivated Land</edomv>
            <edomvd>
Includes herbaceous (cropland) and woody (e.g., orchards,
nurseries, and vineyards) cultivated lands.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>7 Pasture/Hay</edomv>
            <edomvd>
characterized by grasses, legumes or grass-legumes mixtures
planted for livestock grazing or the production of sees or
hay crops.
</edomvd>
            <edomvds>
NLCD 2001 Land Cover Class Definitions, 2004
http://www.mrlc.gov/nlcd_definitions.asp
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>8 Grassland</edomv>
            <edomvd>
Dominated by naturally occurring grasses and non-grasses
(forbs) that are not fertilized, cut, tilled, or planted
regularly.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>9 Deciduous Forest</edomv>
            <edomvd>
Includes areas dominated by single stemmed, woody
vegetation un-branched 0.6 to 1 meter (2 to 3 feet) above
the ground and having a height greater than 5 meters (20
feet).
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>10 Evergreen Forest</edomv>
            <edomvd>
Includes areas in which more than 67 percent of the trees
remain green throughout the year. Both coniferous and
broad-leaved evergreens (greater than 5 meters) are
included in this category.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>11 Mixed Forest</edomv>
            <edomvd>
Contains all forested areas in which both evergreen and
deciduous trees (greater than 5 meters) are growing and
neither predominate.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>12 Scrub/Shrub</edomv>
            <edomvd>
Areas dominated by woody vegetation less than 5 meters in
height. This class includes true shrubs, young trees, and
trees or shrubs that are small or stunted because of
environmental conditions.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>13 Palustrine Forested Wetland</edomv>
            <edomvd>
Includes all non-tidal wetlands dominated by woody
vegetation greater than or equal to 5 meters in height,
and all such wetlands that occur in tidal areas in which
salinity due to ocean-derived salts is below 0.5 parts per
thousand (ppt).
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>14 Palustrine Scrub/Shrub Wetland</edomv>
            <edomvd>
Includes all non-tidal wetlands dominated by woody
vegetation less than or equal to 5 meters in height, and
all such wetlands that occur in tidal areas in which
salinity due to ocean-derived salts is below 0.5 ppt.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>15 Palustrine Emergent Wetland</edomv>
            <edomvd>
Includes all non-tidal wetlands dominated by trees, shrubs,
persistent emergents, emergent mosses, or lichens, and all
such wetlands that occur in tidal areas in which salinity
due to ocean- derived salts is below 0.5 ppt.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>16 Estuarine Forest Wetland</edomv>
            <edomvd>
Includes all tidal wetlands dominated by woody vegetation
greater than or equal to 5 meters in height, and all such
wetlands that occur in tidal areas in which salinity due
to ocean-derived salts is above 0.5 parts per thousand
(ppt).
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>17 Estuarine Scrub/Shrub Wetland</edomv>
            <edomvd>
Includes all tidal wetlands dominated by woody vegetation
less than 5 meters in height, and all such
wetlands that occur in tidal areas in which salinity due
to ocean-derived salts is above 0.5 ppt.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>18 Estuarine Emergent</edomv>
            <edomvd>
Characterized by erect, rooted, herbaceous hydrophytes
(excluding mosses and lichens) that are present for most
of the growing season in most years. Perennial plants
usually dominate these wetlands. All water regimes are
included except those that are sub-tidal and irregularly
exposed.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>19 Unconsolidated Shore</edomv>
            <edomvd>
Characterized by substrates lacking vegetation except for
pioneering plants that become established during brief
periods when growing conditions are favorable. Erosion and
deposition by waves and currents produce a number of
landforms, such as beaches, bars, and flats, all of which
are included in this class.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>20 Bare Land</edomv>
            <edomvd>
Composed of bare soil, rock, sand, silt, gravel, or other
earthen material with little or no vegetation.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>21 Water</edomv>
            <edomvd>
Includes all areas of open water with less than 30 percent
cover of trees, shrubs, persistent emergent plants,
emergent mosses, or lichens.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>22 Palustrine Aquatic Bed</edomv>
            <edomvd>
Includes wetlands and deepwater habitats dominated by
plants that grow principally on or below the surface of
the water for most of the growing season in most years.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>23 Estuarine Aquatic Bed</edomv>
            <edomvd>
Includes widespread and diverse Algal Beds in the Marine
and Estuarine Systems, where they occupy substrates
characterized by a wide range of sediment depths and
textures. They occur in both the sub-tidal and inter-tidal
Subsystems and may grow to depths of 30 m (98 feet).
This class includes kelp forests.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>24 Tundra</edomv>
            <edomvd>
Includes treeless cover beyond the latitudinal limit of
the boreal forest in pole-ward regions and above the
elevation range of the boreal forest in high mountains.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>25 Snow/Ice</edomv>
            <edomvd>
Includes persistent snow and ice that persist for greater
portions of the year.
</edomvd>
            <edomvds>
Dobson, J. et al, NOAA Coastal Change Analysis Program (C-CAP):
Guidance for Regional Implementation, NOAA Technical
Report NMFS 123, U.S. Department of Commerce, April
1995.
</edomvds>
          </edom>
        </attrdomv>
      </attr>
```

**Comment by nvkelso** [comment]
I updated the classes above to split out **glacier** to separate class.

**Comment by mojodna** [comment]
C-CAP mappings (pre-**glacier**):

```python
# C-CAP
# https://coast.noaa.gov/digitalcoast/training/ccap-land-cover-classifications.html
ccap = {
    2: developed,  # Developed, High Intensity
    3: developed,  # Developed, Medium Intensity
    4: developed,  # Developed, Low Intensity
    5: barren,  # Developed, Open Space
    6: cultivated,  # Cultivated Crops
    7: cultivated,  # Pasture/Hay
    8: herbaceous,  # Grassland/Herbaceous
    9: forest,  # Deciduous Forest
    10: forest,  # Evergreen Forest
    11: forest,  # Mixed Forest
    12: shrubland,  # Scrub/Shrub
    13: wetlands,  # Palustrine Forested Wetland
    14: wetlands,  # Palustrine Scrub/Shrub Wetland
    15: wetlands,  # Palustrine Emergent Wetland (Persistent)
    16: wetlands,  # Estuarine Forested Wetland
    17: wetlands,  # Estuarine Scrub/Shrub Wetland
    18: wetlands,  # Estuarine Emergent Wetland
    19: barren,  # Unconsolidated Shore
    20: barren,  # Barren Land
    21: water,  # Open Water
    22: water,  # Palustrine Aquatic Bed
    23: water,  # Estuarine Aquatic Bed
    24: barren,  # Tundra
    25: barren,  # Perennial Ice/Snow
}
```
