### ISSUE TITLE
best way to compose COG from numpy array

### ISSUE THREAD

**Issue by Zaitsev** [mojodna/marblecutter#105]
We have 2d numpy uint8 array that represent black-and-white ENVI image . We use marblecutter-virtual to host tiles that we render tiles with tangram.
Now we use custom script which saves np-array as uint8 3-band ENVI (we duplicate source array to make 3-bands)  and then pipe it gdal translate wrap and addo to produce COG.  
Could you please recommend optimal way to do it?

**Comment by mojodna** [comment]
That's effectively how I'd do it too. The tricky part is turning it into a 3-band image (as you've found). [`gdaldem color-relief`](https://www.gdal.org/gdaldem.html) could be useful for that if you write the array out to a 1-band TIFF, especially if you'd like to produce something other than a greyscale image.

**Comment by Zaitsev** [comment]
Thanks.  If I follow this right,  `gdaldem` will produce indexed colors, since its 1-band uint8 this will not reduce image size.  
We request tile with rgb=1, does marble-tiler just duplicates this 1-st band into rgb-channels? If so, image size is triple of required.

**Comment by mojodna** [comment]
Yes, it does. It uses the "imagery" profile to convert it into something visual: https://github.com/mojodna/marblecutter/blob/5b9040ba6c83562a465eabdbb6e8959e6a8bf041/marblecutter/recipes.py#L95-L168
