### ISSUE TITLE
Getting started with marblecutter

### ISSUE THREAD

**Issue by mccarthyryanc** [mojodna/marblecutter#106]
I have a large collection of cloud optimized geotiffs on S3 that I'd like to serve as web tiles on the fly. It sounds like marblecutter is the tool to do this, but I'm having a hard time following the README and a bit overwhelmed with the various `marblecutter-*` repos. Any tips for a newbie?

**Comment by nvkelso** [comment]
@mojodna for help?

**Comment by mojodna** [comment]
👋 

[marblecutter-virtual](https://github.com/mojodna/marblecutter-virtual) is the package you want. However, if you're ok depending on a shared service, tiles.rdnt.io will do the trick (and is free, hosted by the [Radiant Earth Foundation](http://radiant.earth)).

**Comment by mccarthyryanc** [comment]
Thanks @mojodna! I'll take a look there.
