### ISSUE TITLE
Where can I find Dockerfile and docker-compose.yml mentioned in README?

### ISSUE THREAD

**Issue by adrienDog** [mojodna/marblecutter#110]
Hello,

Thank you very much for your work on Marblecutter. I read that docker-compose is strongly suggested as a tool to try it out.

But I can't find a docker-compose.yml that would indeed provide the building blocks mentioned, such as a PostGIS DB for example.

Nor can I see a Dockerfile to build a Docker image for the Flask application itself.

Can you help me please?
Thank you very much,

Adrien

**Comment by sethfitz** [comment]
Have a look in one of the dependent projects, https://github.com/mojodna/marblecutter-virtual for example. The Flask app included in this repo is just a skeleton, intended to be built on to support specific needs.

**Comment by adrienDog** [comment]
Ah thank you very much Seth :) will go there and close this issue
