### ISSUE TITLE
Review & polish low zoom source transitions

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#17]
Look at zoom 0 - 10 and review which sources are shown at what zooms.

**Comment by nvkelso** [comment]
I'm comparing 256px tiles focused mostly in SF Bay Area (zoomed in and out).

**Prod sources per zoom:**

- https://mapzen.com/documentation/terrain-tiles/data-sources/#what-is-sourced-at-what-zooms
- https://mapzen.com/documentation/terrain-tiles/data-sources/#sources-native-resolution

**Tangram Walkabout testing rigs:**

- http://tangrams.github.io/walkabout-style/#8/-37.298/147.923
- https://mapzen.com/tangram/view/?api=506/766#8/-37.298/147.923

**Dev sources per zoom (2017-07-13):**

tl;dr

- Prod uses GMTED land zooms 0-8 but dev use ETOPO1
    - I don't notice an actual difference at zooms 0-5. That makes sense since the cell size is more generalized then the ETOPO1 source resolution.
    - **I do notice a difference 6-8, though.** I don't understand why this is so. One explanation is dev may be using the 1km GMTED product instead of prod's 250m GTMED product? Or we're using SRTM on prod?
- zoom 9-12+ seem to use the same sources between dev and prod
    - **sometimes I see a xy shift or "jiggle" between dev and prod though? I'll followup with separate issue.**
    - dev NED shows up at zoom 10 where prod documentation says zoom 12, but they're visually identical so suspect the documentation is wrong. 
- New sources at zoom 10+:
    - **in EU we have multiple sources that all come in at zoom 10, ensure Austria data, for instance is priority -1 over the general EU data?** 
        - https://d34o1q5y1d9is8.cloudfront.net/normal/10/548/358.png
        - x-imagery-sources:austria/ogd-10m-at.tif, srtm/N47E012.tif, eudem/eudem_dem_5deg_n45e010.tif
    - **in EU looks like EU DEM fades out back to SRTM at zoom 12+?** check max_zoom for EU DEM.
        - https://d34o1q5y1d9is8.cloudfront.net/normal/11/1092/711.png
        - x-imagery-sources:austria/ogd-10m-at.tif, srtm/N48E012.tif, srtm/N48E011.tif, eudem/eudem_dem_5deg_n45e010.tif
        - https://d34o1q5y1d9is8.cloudfront.net/normal/12/2176/1422.png
        - x-imagery-sources:austria/ogd-10m-at.tif, srtm/N48E011.tif (should still be EU DEM)
    - **in UK I see spikes along Thames river in London at zooms 11 and 12**
        - http://tangrams.github.io/walkabout-style/#12/51.4649/-359.7211
        - Suspect we should bring in the LIDAR data there at least at zoom 12 (the worst spikes) and probably at zoom 11 to minimize spikes. Or do priority swap like fixed SF Bay Area data spikes?
    - I don't see evidence of **Australia** coast LIDAR being added? Still think we should keep it in if we do have it.
    - There are [coastline artifacts](http://tangrams.github.io/walkabout-style/#10/-41.3026/174.2088) around **New Zealand**. Maybe add in one zoom earlier at zoom 10 to minimize those? I see artifacts zoomed in, too... with a lot of sources, do we need to change priorities around? 
    - Keep the **Mexico** data in. Sometimes it's a little funky but overall it's improvement.

SF Bay Area per zoom:

- _zoom 0_: `etopo1/ETOPO1_Bed_g.tif`
- _zoom 1_: `etopo1/ETOPO1_Bed_g.tif`
- _zoom 2_: `etopo1/ETOPO1_Bed_g.tif`
- _zoom 3_: `etopo1/ETOPO1_Bed_g.tif`
- _zoom 4_: `etopo1/ETOPO1_Bed_g.tif`
- _zoom 5_: `etopo1/ETOPO1_Bed_g.tif`
- **zoom 6**: `gmted/30N090W_20101117_gmted_mea075.tif, gmted/30N120W_20101117_gmted_mea075.tif` (different, prod more detailed)
- **zoom 7**: `gmted/30N120W_20101117_gmted_mea075.tif` (different, prod more detailed)
- **zoom 8**: `gmted/30N150W_20101117_gmted_mea075.tif, gmted/30N150E_20101117_gmted_mea075.tif, gmted/30N180W_20101117_gmted_mea075.tif, etopo1/ETOPO1_Bed_g.tif`
- **zoom 9**: `srtm/N39W121.tif, gmted/30N150W_20101117_gmted_mea075.tif`
- **zoom 10**: `ned13/imgn39w122_13.tif, ned13/imgn38w122_13.tif, srtm/N38W122.tif, srtm/N37W122.tif, gmted/30N150W_20101117_gmted_mea075.tif, gmted/30N150E_20101117_gmted_mea075.tif, gmted/30N180W_20101117_gmted_mea075.tif, etopo1/ETOPO1_Bed_g.tif`
- **zoom 11**: `ned_topobathy/ned19_n38x00_w122x25_ca_sanfrancisco_topobathy_2010.tif, ned_topobathy/ned19_n38x00_w122x00_ca_sanfrancisco_topobathy_2010.tif`
- **zoom 12**: `ned_topobathy/ned19_n38x50_w122x50_ca_sanfrancisco_topobathy_2010.tif, ned_topobathy/ned19_n38x50_w122x75_ca_sanfrancisco_topobathy_2010.tif, ned13/imgn39w123_13.tif`

Zoom 6 (dev, GMTED):

<img width="523" alt="screen shot 2017-07-13 at 17 25 15" src="https://user-images.githubusercontent.com/853051/28193267-47a37d60-67f0-11e7-85da-8e87abd3c105.png">

Zoom 6 (prod, I suspect SRTM):

<img width="534" alt="screen shot 2017-07-13 at 17 25 08" src="https://user-images.githubusercontent.com/853051/28193268-47abb28c-67f0-11e7-83e1-3419fed13330.png">

**London data spikes:**

z13 no spikes
<img width="795" alt="screen shot 2017-07-13 at 18 11 12" src="https://user-images.githubusercontent.com/853051/28194134-13319556-67f7-11e7-8848-dd3d8698e409.png">

z12 lots of spikes
<img width="808" alt="screen shot 2017-07-13 at 18 11 07" src="https://user-images.githubusercontent.com/853051/28194136-133add5a-67f7-11e7-98c3-2477c0e3d393.png">

z11 some spikes
<img width="698" alt="screen shot 2017-07-13 at 18 11 03" src="https://user-images.githubusercontent.com/853051/28194135-1338583c-67f7-11e7-8714-7a5ddf7d1111.png">

**Comment by iandees** [comment]
@nvkelso when you post screenshots, can you please include links to the areas that you're screenshotting?

**Comment by iandees** [comment]
It would also help if you could highlight or circled features you're talking about. I think I know what you mean by "spikes" but it would be helpful to be explicit.

**Comment by iandees** [comment]
### Spikes in the Thames

Circled in red here:
![image](https://user-images.githubusercontent.com/261584/28216410-a3da4aca-687f-11e7-96b0-ea6d382eeb2f.png)
*From [hillshade/12/2050/1362](https://terrain-lambda.dev.mapzen.com/hillshade/12/2050/1362.png)*

The tiler used these sources for this tile: srtm/N51E000.tif, srtm/N51W180.tif, srtm/N51E179.tif, eudem/eudem_dem_5deg_n50e000.tif (note that these are ordered from "bottom to top"; each layer listed here is pasted on top of the previous ones until we run out of source candidates or we've filled the entire image with valid data)

#### srtm/N51E000.tif

This image looks OK with no anomalies or artifacts in the data.

![image](https://user-images.githubusercontent.com/261584/28217195-4cebecde-6882-11e7-85cb-9850b2b79667.png)

The red square is the bounding box of the tile. The image is rendered as hillshade in QGIS.

#### srtm/N51W180.tif, srtm/N51E179.tif

Both of these images seem to have screwy or broken bounding boxes and probably shouldn't have been included in the source candidate selection because there images contribute no data to the tile. They probably showed up because they abut the antemeridian and the buffer we apply broke the footprint geometry.

#### eudem/eudem_dem_5deg_n50e000.tif

![image](https://user-images.githubusercontent.com/261584/28217266-8de70390-6882-11e7-8eac-9bc1b1042634.png)

This image appears OK, but I think this is the source of the funniness for two reasons:

1. The `srtm` data uses `nodata` values to represent the surface of the River Thames and the `eudem` data uses zero.
1. The riverbank mask of the River Thames is different between the two datasets, so little bits of the `eudem` shoreline are visible behind the `srtm` data.

In this QGIS screenshot, the `eudem` hillshade is tinted green and the `srtm` hillshade is tinted red:

![image](https://user-images.githubusercontent.com/261584/28217612-bc2ce372-6883-11e7-9109-c093c379ab81.png)

**Comment by nvkelso** [comment]
Sure, I can include more tile coords / annotated screenshots in the future.

> The srtm data uses nodata values to represent the surface of the River Thames and the eudem data uses zero.

Should we be setting SRTM nodata to `0` instead of `-9999` or whatever the interpolator is defaulting to?

I suspect a lot of the problems reported in https://github.com/mojodna/marblecutter/issues/17#issuecomment-315246710 resolve around curation of `min_zoom` and priority.

Can you report table of source, count, min_zoom, max_zoom, and priority for review please? Similar to what you did in https://github.com/mojodna/marblecutter/issues/7#issuecomment-311174031.

```
 source        | count
----------------------+-------
 eudem                |    72
 ned                  |  7919
 ned13                |  1262
 ned_topobathy        |    35
 nrcan_cdem           |  1021
 pgdc_5m              |  3743
 srtm                 | 14297
```

I suspect `eudem` should match `ned` on zoom ranges and priority, for example. And other "good" national sources like Austria should match range of "good" sources like `ned13`.

**Comment by iandees** [comment]
Here's the min/max zoom per source as it stands right now (`res` is the 'rounded resolution'):

|        source        | count  | min_zoom | max_zoom | res  |
|----------------------+--------+----------+----------+------|
| etopo1               |      1 |        0 |       15 | 1853 |
| gmted                |     22 |        4 |        8 |  927 |
| gmted                |   1788 |        6 |       10 |  232 |
| nrcan_cdem           |     13 |        7 |       20 |   84 |
| nrcan_cdem           |      4 |        7 |       20 |   92 |
| nrcan_cdem           |      2 |        7 |       20 |   93 |
| mgg_greatlakes       |      8 |        8 |       11 |   93 |
| nrcan_cdem           |      2 |        8 |       20 |   40 |
| nrcan_cdem           |     26 |        8 |       20 |   41 |
| nrcan_cdem           |    209 |        8 |       20 |   43 |
| nrcan_cdem           |     20 |        8 |       20 |   44 |
| nrcan_cdem           |      9 |        8 |       20 |   45 |
| nrcan_cdem           |      3 |        8 |       20 |   46 |
| nrcan_cdem           |      3 |        8 |       20 |   68 |
| eudem                |    138 |        9 |       20 |   31 |
| nrcan_cdem           |   1090 |        9 |       20 |   23 |
| nrcan_cdem           |     11 |        9 |       20 |   37 |
| srtm                 | 130837 |        9 |       20 |   31 |
| austria              |     12 |       10 |       14 |   10 |
| kartverket           |    297 |       10 |       14 |   10 |
| ned13                |  10097 |       10 |       20 |   10 |
| ned_topobathy        |     55 |       10 |       20 |    3 |
| geosciences_au       |     98 |       11 |       15 |    5 |
| mx_lidar             |   2516 |       11 |       20 |    5 |
| ned                  |  37285 |       11 |       20 |    3 |
| nzlinz               |    905 |       11 |       20 |    8 |
| pgdc_5m              | 387526 |       11 |       20 |    5 |
| mgg_inundation_sandy |     57 |       12 |       16 |    3 |
| uk_lidar             |   8507 |       13 |       17 |    2 |

**Comment by nvkelso** [comment]
_Slack integration test_

**Comment by nvkelso** [comment]
_no, really_

**Comment by nvkelso** [comment]
This will take more processing time, but result in less data spikes (our top customer complaint about v2):

Let's move all these up to min_zoom `10`:

|        source        | count  | min_zoom | max_zoom | res  |
|----------------------|--------|----------|----------|------|
| geosciences_au       |     98 |       11 |       15 |    5 |
| mx_lidar             |   2516 |       11 |       20 |    5 |
| ned                  |  37285 |       11 |       20 |    3 |
| nzlinz               |    905 |       11 |       20 |    8 |
| pgdc_5m              | 387526 |       11 |       20 |    5 |
| mgg_inundation_sandy |     57 |       12 |       16 |    3 |
| uk_lidar             |   8507 |       13 |       17 |    2 |

**Comment by mojodna** [comment]
`max_zoom` should also be bumped up to 20 for all of them.

**Comment by nvkelso** [comment]
Might need to end up punting Great Lakes data for this build.

We should just remove `mgg_inundation_sandy` from the build (it is not bare earth).

**Comment by iandees** [comment]
Made the changes that [Nathaniel suggested above](https://github.com/mojodna/marblecutter/issues/17#issuecomment-315419423):

```
footprints=> update footprints set min_zoom=10, max_zoom=20 where source='geosciences_au';
UPDATE 98
footprints=> update footprints set min_zoom=10, max_zoom=20 where source='mx_lidar';
UPDATE 2516
footprints=> update footprints set min_zoom=10, max_zoom=20 where source='ned';
UPDATE 37285
footprints=> update footprints set min_zoom=10, max_zoom=20 where source='nzlinz';
UPDATE 905
footprints=> update footprints set min_zoom=10, max_zoom=20 where source='pgdc_5m';
UPDATE 387526
footprints=> update footprints set min_zoom=10, max_zoom=20 where source='mgg_inundation_sandy';
UPDATE 57
footprints=> update footprints set min_zoom=10, max_zoom=20 where source='uk_lidar';
UPDATE 8507
footprints=> update footprints set min_zoom=6, max_zoom=20 where source='srtm';
UPDATE 130837
footprints=> update footprints set min_zoom=4, max_zoom=15 where round(resolution)=232 and source='gmted';
UPDATE 1788
footprints=> update footprints set min_zoom=8, max_zoom=20 where source='mgg_greatlakes';
UPDATE 8
footprints=> update footprints set min_zoom=10, max_zoom=20 where source='austria';
UPDATE 12
footprints=> update footprints set min_zoom=10, max_zoom=20 where source='kartverket';
```

**Comment by iandees** [comment]
Introducing SRTM at z6 caused the tiler to time out because it was pulling in 25+ sources for a single tile. I bumped it down to z7:

```
footprints=> update footprints set min_zoom=7, max_zoom=20 where source='srtm';
UPDATE 130837
```

**Comment by iandees** [comment]
Actually, went to min zoom 8, not just 7.

**Comment by nvkelso** [comment]
I'm reviewing this today, so far so good.

**Comment by nvkelso** [comment]
- Zoom 6 and 7 are still a little blurry but workable 👍
- Zoom 8 is now sharper with SRTM, matches prod 👍 
- Zoom 10+ with Austria data is working 👍
- Zoom 11/12 in UK mostly no spikes along Thames river in London 👍
- Zoom 12+ in EU now includes  EU DEM 👍
- Zoom 15 in EU on Germany-Austria border seriously funky (zoom 14- is fine) 😨
    - http://localhost:4000/#15/47.5846/13.0559
    - https://k6yfeg1cx6.execute-api.us-east-1.amazonaws.com/Prod/normal/15/17571/11446.png
    - ![11446](https://user-images.githubusercontent.com/853051/28352815-70fba798-6c0d-11e7-8c11-9daf99637825.png)
- I don't see evidence of Australia coast LIDAR being added? 😨
    - http://localhost:4000/#15/-36.9464/139.7004
    - https://k6yfeg1cx6.execute-api.us-east-1.amazonaws.com/Prod/normal/14/14553/10005.png
    - Coastline near there is a mess. 😨
- Zoom 9+ there look to be **more** coastline artifacts around New Zealand now? 😨
   - https://k6yfeg1cx6.execute-api.us-east-1.amazonaws.com/Prod/normal/10/1008/641.png
   - There are a _lot_ of sources used for this one tile, maybe the NZ LINZ source needs to be higher priority? `nzlinz/lds-tile-mk-GTiff.tif, srtm/S42E174.tif, gmted/50S150E_20101117_gmted_mea075.tif, gmted/50S180W_20101117_gmted_mea075.tif, etopo1/ETOPO1_Bed_g.tif`
    - <img width="765" alt="screen shot 2017-07-18 at 23 23 16" src="https://user-images.githubusercontent.com/853051/28353338-21b07e36-6c10-11e7-841f-f2b54eadeacb.png">
- Still have Mexico data 👍
- Remove mgg_greatlakes (that one funky zone is in prod, too) 👍
- Remove sandy_innundatation 👍
- NYC bathymetry doesn't look good, but neither did v1?! 😨 
    - http://localhost:4000/#13/40.7089/-74.0010
    - https://k6yfeg1cx6.execute-api.us-east-1.amazonaws.com/Prod/normal/13/2412/3079.png
    - `ned13/USGS_NED_13_n41w074_IMG.tif, ned13/USGS_NED_13_n41w075_IMG.tif, srtm/N40W074.tif, srtm/N40W075.tif, gmted/30N090W_20101117_gmted_mea075.tif, gmted/30N150E_20101117_gmted_mea075.tif, gmted/30N180W_20101117_gmted_mea075.tif, etopo1/ETOPO1_Bed_g.tif`
- Norway data on land is looking good 👍
- Some Norway data in water is not looking good 😨
    - http://localhost:4000/#9/58.8961/10.1486
    - <img width="884" alt="screen shot 2017-07-18 at 23 17 10" src="https://user-images.githubusercontent.com/853051/28353180-5d7ba644-6c0f-11e7-9a7c-b58c31e0a3d2.png">
- Canada data on land is looking good 👍
- Canada bathy data just seems to be missing zoom 9+ (prod din't look great, though) See Vancouver. 😨

**Comment by nvkelso** [comment]
**Higher priority:**

- Australia-Germany boundary at zoom 15 - paging @mojodna  and @iandees 
- New Zealand coastline mess / priority ordering - paging @iandees 

The rest are mostly bathy funk that was just different bathy funk before. We should document with followup issues only - @nvkelso.

**Comment by nvkelso** [comment]
- Verified Australia coastal LiDAR 👍
    - NT: https://terrain-lambda.dev.mapzen.com/hillshade/preview#14/-12.5773/130.9878
    - VIC: https://terrain-lambda.dev.mapzen.com/hillshade/preview#13/-38.347/142.208

**Comment by nvkelso** [comment]
Followup issues filed in #31, #32, and #33. Closing.
