### ISSUE TITLE
Janky data spikes near Pittsburgh, Calif.

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#2]
_Migrated from: https://github.com/hotosm/oam-dynamic-tiler/issues/41_

I'm seeing occasional weird data inland, here north of Pittsburgh in the delta area north of SF in the normal tiles, but I think this is more a general data source combining / no-data filling problem.

These are _new_ artifacts compared to **joerd** – but **marbletiler** seems to have fixed other ocean land seam artifacts.

![pasted image at 2017_06_06 10_30 pm](https://user-images.githubusercontent.com/853051/26899915-7c55bb90-4b85-11e7-8232-03d678d7eed7.png)

**Comment by nvkelso** [comment]
This is still a problem.

**Comment by nvkelso** [comment]
I suspect this is fixed at zoom 11+ with https://github.com/mojodna/marblecutter/issues/6, but it's still a problem at zoom 10 here – and will be a problem in places we only have SRTM data.

**Comment by nvkelso** [comment]
@mojodna Any ideas about this one?

**Comment by mojodna** [comment]
Can you highlight the artifacts you're seeing? I haven't looked at this area enough to know what's what.

**Comment by mojodna** [comment]
I'm potentially seeing related artifacts (I'm not sure these are artifacts or if it's where inland bathymetry data ends):

![image](https://user-images.githubusercontent.com/45/28096529-65fbccf6-665e-11e7-8204-8d5823aeffbd.png)

https://d34o1q5y1d9is8.cloudfront.net/hillshade/preview?retina=true#12/38.0196/-122.0784

**Comment by mojodna** [comment]
Or where multiple sources are available at the same resolution and they're getting prioritized differently.

**Comment by mojodna** [comment]
I ran `update footprints set priority=1 where source='ned'` to effectively increase the priority of data w/ bathymetry where rounded data resolution matches.

**Comment by nvkelso** [comment]
I've added red annotations on my original screenshot:

![data-funk-annotated](https://user-images.githubusercontent.com/853051/28176253-92354560-67ab-11e7-95cc-b83904021b05.png)

**Comment by nvkelso** [comment]
Seems fixed! Same area using the new dev tiles:

<img width="1074" alt="screen shot 2017-07-13 at 09 19 13" src="https://user-images.githubusercontent.com/853051/28176486-735ed34e-67ac-11e7-8f29-6c67c3cf9f46.png">

**Comment by nvkelso** [comment]
@mojodna to fix this in Mapzen's footprint database is the only thing required to run the following?

`set priority=1 where source='ned'`

Keeping this issue open until fix is applied verified in Mapzen's dev stack.

**Comment by nvkelso** [comment]
Seth's fix was applied to Mapzen's footprint database and things look good. Verified.
