### ISSUE TITLE
Remove timers image header info for prod build

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#21]
Nice to keep as dev option, but we shouldn't export those for prod build:

https://d34o1q5y1d9is8.cloudfront.net/normal/9/84/194.png

```
Request Headers
x-timers:get sources: 0.00, composite: 0.32, transform: 0.07, crop: 0.00, format: 0.06
```

**Comment by iandees** [comment]
These are gone in the code and won't be included in the S3 build.
