### ISSUE TITLE
xy "jiggle" between dev and prod

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#22]
Sometimes I see a xy shift or "jiggle" between dev and prod at mid-zooms (maybe low zooms, too?)

- http://tangrams.github.io/walkabout-style/#9/38.8130/-122.6321
- https://mapzen.com/tangram/view/?api=506/766#9/38.8130/-122.6321

This is using the 256 pixel endpoints.

![zoom-9-jiggle](https://user-images.githubusercontent.com/853051/28195129-3df67774-67fd-11e7-956b-54a757f7a6b3.gif)

**Comment by mojodna** [comment]
I'll revisit this after #20, as it looks like it may be related to tile windows.

**Comment by mojodna** [comment]
Updating to `rasterio@master` didn't change things:

![compare](https://user-images.githubusercontent.com/45/28446230-482f6bfc-6d7e-11e7-853f-35fab3de7361.png)

**Comment by mojodna** [comment]
I'm having a hard time determining which is more correct. It's possible that the difference results from reading different parts of the source image (here 1px = 16+ pixels in the original DEM), depending on which resampling method was used to produce overviews (it was previously using nearest-neighbour, now it's using lanczos). The jitter seems to be less than a pixel, so it doesn't appear to be an offset issue.

@nvkelso is this a problem or a curiosity?

**Comment by nvkelso** [comment]
As it still seems to mostly lineup with road lines and water lines & polygons I think it's more of a curiosity. If it also was evident at higher zooms (like max_zoom 15) than I'd say more of a problem, but so far I haven't seen that to be the case.

Closing this issue (it can be re-opened in the future if turns out it's a problem).

**Comment by mojodna** [comment]
I'm seeing something similar in QGIS when overviews are in use, so I suspect that it has something to do with GDAL's handling of overviews (either creation or reading) when internally tiling.

**Comment by mojodna** [comment]
![original](https://user-images.githubusercontent.com/45/29423219-c6a33600-832f-11e7-888e-37f9b6fcf6ae.png)

![oam](https://user-images.githubusercontent.com/45/29423218-c6a15a9c-832f-11e7-940f-11f203b3a345.png)

**Comment by mojodna** [comment]
![overviews](https://user-images.githubusercontent.com/45/29804133-6ade75be-8c35-11e7-9e7b-9d3fc2b079af.gif)
