### ISSUE TITLE
Add ability to disable footprints in DB, not use them for rendering 

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#23]
Sometimes we import sources that aren't actually useful (like the hurricane sandy data). Rather than orphaning them in the S3 bucket without a footprint, we should add the ability to disable footprints.

- [x] Add an enabled flag to existing footprints
- [x] For sandy footprints set that to disabled
- [x] Add logic to utilize the enabled flag (to by default skip enabled=false sources, maybe this is a config option to force using all sources?)
- [x] Add logic in transcoding to input footprints with enabled=true

**Comment by iandees** [comment]
Ran this on the existing DB:

```sql
alter table footprints add column enabled boolean default true;
```

**Comment by iandees** [comment]
Updated Sandy footprints:

```sql
footprints=> update footprints set enabled='f' where source='mgg_inundation_sandy';
UPDATE 57
```

**Comment by iandees** [comment]
The code changes for this are in the Mapzen lambda tiler and will be used in future S3 builds.
