### ISSUE TITLE
Extend transcoding step to only generate footprints

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#29]
Sometimes we need to regenerate footprints separately from the transcoding step (which now bundles transcoding and exporting footprints to the database). This issue covers unbundling those steps.

**Comment by nvkelso** [comment]
This is still needed via comment in PR https://github.com/mojodna/marblecutter/pull/30#issuecomment-316567102

**Comment by iandees** [comment]
For what it's worth, I skipped this because adding the flag was more work then just kicking off another re-transcode that ran last night.

**Comment by nvkelso** [comment]
Closing as process changed.
