### ISSUE TITLE
Funk along New Zealand coast

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#32]
- Zoom 9+ there look to be **more** coastline artifacts around New Zealand now? 😨
   - https://k6yfeg1cx6.execute-api.us-east-1.amazonaws.com/Prod/normal/10/1008/641.png
   - There are a _lot_ of sources used for this one tile, maybe the NZ LINZ source needs to be higher priority? `nzlinz/lds-tile-mk-GTiff.tif, srtm/S42E174.tif, gmted/50S150E_20101117_gmted_mea075.tif, gmted/50S180W_20101117_gmted_mea075.tif, etopo1/ETOPO1_Bed_g.tif`
    - <img width="765" alt="screen shot 2017-07-18 at 23 23 16" src="https://user-images.githubusercontent.com/853051/28353338-21b07e36-6c10-11e7-841f-f2b54eadeacb.png">

Following up from: https://github.com/mojodna/marblecutter/issues/17.

Could be "fixed" with the smaller footprints being updated in https://github.com/mojodna/marblecutter/issues/28? Let's deploy #28 and then retest this New Zealand issue.

**Comment by iandees** [comment]
This is pretty ugly:

![image](https://user-images.githubusercontent.com/261584/28462638-091afab4-6dea-11e7-9bd5-467e78c3bfb4.png)

([tile](https://terrain-lambda.dev.mapzen.com/normal/11/2015/1282.png) around [here](https://terrain-lambda.dev.mapzen.com/normal/preview#11/-41.2535/174.2301), using `nzlinz/lds-tile-mk.tif, nzlinz/lds-tile-mj.tif, srtm/S42E174.tif, gmted/50S150E_20101117_gmted_mea075.tif, etopo1/ETOPO1_Bed_g.tif`)

I think this is a case where the LINZ data has a different shoreline mask than the data "under" it so the lower-resolution pixels are sticking out with a different value.

**Comment by iandees** [comment]
This screenshot from QGIS shows a zoomed in piece of this tile. The shoreline exposes 3 different datasets at different resolutions, and when they're composited it creates artifacts like we see in the end product.

![image](https://user-images.githubusercontent.com/261584/28463499-ac1d25d0-6dee-11e7-9d72-bb78fba5f437.png)
(green and red is LINZ, blue is SRTM, turquoise is GMTED)

**Comment by iandees** [comment]
This particular funk was fixed by adjusting the GMTED to have a different max zoom:

```
footprints=> update footprints set min_zoom=4, max_zoom=10 where round(resolution)=232 and source='gmted';
UPDATE 96
```

Resulting in [this tile](https://terrain-lambda.dev.mapzen.com/normal/11/2015/1282.png) using `nzlinz/lds-tile-mk.tif, nzlinz/lds-tile-mj.tif, srtm/S42E174.tif, etopo1/ETOPO1_Bed_g.tif`. There's still some oddness around the coast, but at least it doesn't *look* bad.

![image](https://user-images.githubusercontent.com/261584/28464447-4921a424-6df3-11e7-86c3-fe95df06452c.png)

**Comment by nvkelso** [comment]
Is there a way to still preserve GMTED at latitudes higher than 60°? So if > 60° or < -60° then max zoom 15, else max_zoom 10?

**Comment by iandees** [comment]
![image](https://user-images.githubusercontent.com/261584/28484563-14df8f52-6e41-11e7-92dd-630ab52498d6.png)
(GMTED footprints, light blue is resolution ~232, dark blue is resolution ~927)

So I think we're going to put GMTED over ETOPO where we don't have PGDC polar data. In the south, we'll use ETOPO after GMTED stops at z8 right now. If we change the ~927 resolution data to max_zoom z15 we shouldn't see ETOPO at all down there.

**Comment by nvkelso** [comment]
Interesting. I guess the British didn't want to open source their higher resolution Antarctica data to GMTED!

**Comment by iandees** [comment]
PS: Looks like I missed reprocessing a tile of GMTED in the lower-left there. I re-ran it real quick and now it looks like this:

![image](https://user-images.githubusercontent.com/261584/28485191-b561d68e-6e45-11e7-8805-708700ca21b6.png)

**Comment by nvkelso** [comment]
> So I think we're going to put GMTED over ETOPO where we don't have PGDC polar data. In the south, we'll use ETOPO after GMTED stops at z8 right now. If we change the ~927 resolution data to max_zoom z15 we shouldn't see ETOPO at all down there.

- [ ] Agree we should set GMTED to `max_zoom` **15** for `927 meter` resolution so we always get good data down in **Antarctica**.

I've highlighted the image below in `#ff0000` RED for areas ±60° latitude and marked the middle zone in `#0000ff` BLUE for the _whole_ tiles that are giving us problems.

- [ ] It sounds like for `#0000ff` BLUE tiles since **srtm** `min_zoom` is **9** then we want to set those GMTED tiles at `232 meter` resolution to `max_zoom` **9** so there isn't any overlap?

- [ ]  For the dozen or so GMTED tiles at `232 meter` resolution that are above and below +60° latitude I guess we make them `max_zoom` **15**?

![red-blue-gmted](https://user-images.githubusercontent.com/853051/28485307-6c8a03ae-6e2d-11e7-858d-81d9158e9979.gif)

**Comment by nvkelso** [comment]
New Zealand is better but not great. Will retest after **gmted** footprints are updated.

**Comment by iandees** [comment]
#### NED19 timeouts

NED19 coming in at z10 was causing some tiles to timeout because there were too many sources to read in for a single tile. I changed them to start at z11:

```
footprints=> update footprints set min_zoom=11, max_zoom=20 where source='ned';
UPDATE 7914
```

#### Antarctica GMTED

Updated southern 927 GMTED images to go to z15.

```
footprints=> update footprints set min_zoom=4, max_zoom=15 where round(resolution)=927 and source='gmted';
UPDATE 12
```

####

**Comment by iandees** [comment]
#### Whole GMTED sources between 60/-60

Update the GMTED sources wholly contained between +60/-60 latitude to `max_zoom` 9:

```
footprints=> update footprints set max_zoom=9 where wkb_geometry @ ST_MakeEnvelope(-180, -60, 180, 60, 4326) and source='gmted';
UPDATE 61
```

#### Whole GMTED sources above 60/below -60

Update the GMTED sources wholly above +60 and below -60 latitude to `max_zoom` 15:

```
footprints=> update footprints set max_zoom=15 where not wkb_geometry @ ST_MakeEnvelope(-180, -60, 180, 60, 4326) and source='gmted';
UPDATE 35
```

**Comment by iandees** [comment]
New sources chart:

|    source     | count | min_zoom | max_zoom | res  |
|---------------|-------|----------|----------|------|
| etopo1        |     1 |        0 |       15 | 1853 |
| gmted         |    61 |        4 |        9 |  232 |
| gmted         |    12 |        4 |       15 |  927 |
| gmted         |    23 |        4 |       15 |  232 |
| nrcan_cdem    |     9 |        7 |       20 |   84 |
| nrcan_cdem    |     2 |        7 |       20 |   93 |
| nrcan_cdem    |     2 |        7 |       20 |   92 |
| srtm          | 14297 |        7 |       20 |   31 |
| nrcan_cdem    |    12 |        8 |       20 |   41 |
| nrcan_cdem    |   120 |        8 |       20 |   43 |
| nrcan_cdem    |     9 |        8 |       20 |   44 |
| nrcan_cdem    |     1 |        8 |       20 |   40 |
| nrcan_cdem    |     6 |        8 |       20 |   45 |
| nrcan_cdem    |     1 |        8 |       20 |   68 |
| nrcan_cdem    |     3 |        8 |       20 |   46 |
| eudem         |    80 |        9 |       20 |   31 |
| nrcan_cdem    |   856 |        9 |       20 |   23 |
| nrcan_cdem    |     6 |        9 |       20 |   37 |
| austria       |     1 |       10 |       20 |   10 |
| geoscience_au |     3 |       10 |       20 |    5 |
| kartverket    |   255 |       10 |       20 |   10 |
| mx_lidar      |  2503 |       10 |       20 |    5 |
| ned13         |  1255 |       10 |       20 |   10 |
| ned_topobathy |    35 |       10 |       20 |    3 |
| nzlinz        |   115 |       10 |       20 |    8 |
| pgdc_5m       |  3806 |       10 |       20 |    5 |
| uk_lidar      |  1518 |       10 |       20 |    2 |
| ned           |  7914 |       11 |       20 |    3 |

**Comment by nvkelso** [comment]
This is ready for me to review again.

**Comment by nvkelso** [comment]
I'm seeing slight improvements, but still some funk. I think anything remaining is related to https://github.com/mojodna/marblecutter/issues/33 so closing this issue.

10/-41.2732/174.4766

<img width="1035" alt="screen shot 2017-07-25 at 11 33 06" src="https://user-images.githubusercontent.com/853051/28587741-0d20e434-712d-11e7-8e6a-01d76cddff79.png">
