### ISSUE TITLE
Add endpoint to query what sources are available for an z/x/y tile 

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#36]
In the service of metadata, documentation, and a live debug tool.

**Comment by mojodna** [comment]
There are now both [GeoJSON](https://github.com/mojodna/marblecutter-tilezen/blob/95bca2a/tilezen/web.py#L143) and [JSON](https://github.com/mojodna/marblecutter-tilezen/blob/95bca2a/tilezen/web.py#L165) endpoints containing source info (and geometries, for GeoJSON) to both help debugging and support `RemoteCatalog` implementations.
