### ISSUE TITLE
Janky Manhattan coverage (buildings on west side of island)

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#39]
https://d34o1q5y1d9is8.cloudfront.net/hillshade/preview#13/40.7307/-74.0063

The west side of the island seems to show building shapes while the east side does not. Is there a source we could remove to fix that up?

<img width="712" alt="screen shot 2017-07-21 at 17 16 52" src="https://user-images.githubusercontent.com/853051/28486608-8070a7f0-6e38-11e7-87db-64855b5886af.png">

<img width="1202" alt="screen shot 2017-07-21 at 17 17 46" src="https://user-images.githubusercontent.com/853051/28486616-8c263826-6e38-11e7-82be-25a040da26bc.png">

**Comment by iandees** [comment]
The yucky Manhattan image there is coming from a NED 1/3 image that seems to have terrible building removal:

![image](https://user-images.githubusercontent.com/261584/28575087-deee64a6-711d-11e7-9705-639a97133b53.png)

**Comment by iandees** [comment]
I spent a couple minutes looking for better New York/Manhattan data and found [1m data from USGS/New York State](https://orthos.dhses.ny.gov/?Extent=-9603624.133747088,4774299.7366908705,-7659066.134172721,5795498.434580554&Layers=07_meter_dem_index_usgs,1_meter_dem_index_fema,1_meter_dem_index_usgs,1_meter_dem_index_tidal_water,1_meter_dem_index_hydro_flattened,1_meter_dem_index_usda_utm18n,1_meter_dem_index_usda_utm17n,1_meter_dem_index_nys,2_meter_dem_index_ne_lidar,2_meter_dem_index_nys,2_meter_dem_index_fema,2_meter_dem_index_monroe_county,2_meter_dem_index_tompkins_county,2_meter_dem_index_erie_county&layerGroups=DEMIndexes,Orthoimagery&rightMenu=0#) that looks like this:

![image](https://user-images.githubusercontent.com/261584/28575903-4fc39802-7120-11e7-9f41-f5816e26f8f2.png)

**Comment by nvkelso** [comment]
Let's find either a NED source that is bad to disable, a new NED source that wasn't transcoded to replace, or just disable that NED bad source and let the SRTM show thru. I don't want to add new sources to the equation.

**Comment by iandees** [comment]
The NED 1/3 source image that's got building holes in it is `USGS_NED_13_n41w075_IMG.tif`.

*Hillshade screenshots from QGIS with the bounding box for tile 14/4823/6159*

This is what we have in our transcoded bucket right now:
![image](https://user-images.githubusercontent.com/261584/28589486-6313ccca-714c-11e7-8bcc-34d6d4eea095.png)

This is `USGS NED 1/3 arc-second n41w075 1 x 1 degree IMG 2017` downloaded from the National Map viewer just now:
![image](https://user-images.githubusercontent.com/261584/28589623-e22aedcc-714c-11e7-9886-feb61011581f.png)

This is `USGS NED n41w075 1/3 arc-second 2013 1 x 1 degree ArcGrid` downloaded from the National Map viewer just now:
![image](https://user-images.githubusercontent.com/261584/28589819-aead243c-714d-11e7-9166-808970e5ff24.png)

It looks like there is a NED 1/9 image whose footprint says it covers eastern Manhattan ([`ned19_n40x75_w074x00_ny_nassauco_2010`](https://www.sciencebase.gov/catalog/item/581d2b84e4b08da350d63f48)), but it doesn't have any data over Manhattan.

**Comment by nvkelso** [comment]
What does SRTM only look like there?

**Comment by iandees** [comment]
SRTM looks like this (same tile boundary in the frame, there):

![image](https://user-images.githubusercontent.com/261584/28591508-02e9b0d2-7154-11e7-8652-a7da7f7a3fe6.png)

**Comment by nvkelso** [comment]
Let's just disable the NED which overlap here and see how the SRTM is in
practice.

**Comment by iandees** [comment]
I disabled the NED 1/3 image and this is what [downtown Manhattan](https://terrain-lambda.dev.mapzen.com/hillshade/preview#13/40.7119/-74.0075) looks like now:

![image](https://user-images.githubusercontent.com/261584/28594581-7b050a80-715e-11e7-8605-eeaf1a1eb672.png)

**Comment by nvkelso** [comment]
Is the cruft coming from the ned source or SRTM (in lower tip of Manhattan)?

`x-imagery-sources:ned/ned19_n40x75_w074x25_nj_northeast_2007.tif, srtm/N40W075.tif, etopo1/ETOPO1_Bed_g.tif`

![3080](https://user-images.githubusercontent.com/853051/28594774-f7eef1fa-7145-11e7-8bc4-74d4d1fcd591.png)

**Comment by iandees** [comment]
The islands in the bay there are SRTM poking through ETOPO:

![image](https://user-images.githubusercontent.com/261584/28595824-aad15f52-7163-11e7-9b58-6b9898c32181.png)

**Comment by iandees** [comment]
Sorry, no. Those are islands in SRTM sitting *on top of* ETOPO.

**Comment by nvkelso** [comment]
Let's try re-enabling the NED – maybe it looks better than SRTM IRL without the tinfoil QGIS hillshading?

**Comment by iandees** [comment]
Re-enabling NED looks like this:

![image](https://user-images.githubusercontent.com/261584/28902919-a1f83bf2-77c7-11e7-8db4-d0930512ece8.png)

**Comment by nvkelso** [comment]
I don't see this problem in the latest dev builds, closing.
