### ISSUE TITLE
Normal format (transformed) PNGs are fuzzy and muted

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#4]
_Ported from https://github.com/hotosm/oam-dynamic-tiler/issues/39._

Looks like MarbleTiler fork is producing different normals than Joerd. There are probably more than one way of calculating these, but the output of Joerd is better for presentation cartography like Walkabout style and MarbleTiler should better match that output.

Specifically, MarbleTiler dev (top again) seems to have less exaggeration on the terrain / less details (compared to joerd prod)? Is the kernel size larger in MarbleTiler versus Joerd? That may account for more generalized looking relief.

- MarbleTiler: https://github.com/mojodna/marblecutter/blob/mapzen/marblecutter/transformations/normal.py
- Joerd: https://github.com/tilezen/joerd/blob/master/joerd/output/normal.py

**Example 1:** 

- https://d34o1q5y1d9is8.cloudfront.net/normal/6/33/22.png
- http://tile.mapzen.com/mapzen/terrain/v1/normal/6/33/22.png (requires API key)

![dev-22](https://user-images.githubusercontent.com/853051/26897818-a3868980-4b7e-11e7-9b66-31344c765844.png) `marbletiler` _fuzzy, less exaggeration_
![prod-22](https://user-images.githubusercontent.com/853051/26897816-a2db2888-4b7e-11e7-809c-73c3eaa5f47f.png) `joerd` _crispier (more detail), more exaggeration_

**Example 2:**

- https://d34o1q5y1d9is8.cloudfront.net/normal/10/163/395.png
- http://tile.mapzen.com/mapzen/terrain/v1/normal/10/163/395.png (requires API key)

![dev-395](https://user-images.githubusercontent.com/853051/26898775-ebbd111c-4b81-11e7-919d-05ff7dc40e74.png) `marbletiler`
![prod-395](https://user-images.githubusercontent.com/853051/26898774-ebb4734a-4b81-11e7-9a2a-6ac890829798.png) `joerd`

**Walkabout showing Example 2:**

`marbletiler` ![pasted image at 2017_06_06 10_27 pm](https://user-images.githubusercontent.com/853051/26898807-01f42614-4b82-11e7-9e93-b6e6bf25bb54.png)
`joerd` ![pasted image at 2017_06_06 10_27 pm 1](https://user-images.githubusercontent.com/853051/26898806-01f2e34e-4b82-11e7-886b-ff93e9f7fecf.png)

**Comment by iandees** [comment]
For a more recent reference, here is output from the lambda tiler now:

[url]()

**Comment by nvkelso** [comment]
This is still a problem. I suspect it's compounded by not having consistent exaggeration applied in https://github.com/mojodna/marblecutter/issues/3 (as in first that one first, retest), but I suspect there are some data differences, too.

**Comment by iandees** [comment]
An anecdote: I took the URL [from my comment above](https://github.com/mojodna/marblecutter/issues/4#issuecomment-310497123) and added `@2x` to bump the resolution. Then I copied that 512x512 pixel image into an image manipulation program and sized it back down to 256x256 pixels I get this:

![image](https://user-images.githubusercontent.com/261584/27875245-807a22c2-6180-11e7-8668-651c2dea46e5.png)

That image looks to be crisp like @nvkelso's image in the description of this bug. I wonder if this is a problem related to resolution?

**Comment by mojodna** [comment]
It is indeed resolution-related (and a side-effect of trying to use resolution for everything internally rather than target zoom as distinct from target output size). The 1x-scaled version only uses `etopo1/ETOPO1_Bed_g.tif`, the 2x-scaled version uses `gmted/30N180W_20101117_gmted_mea075.tif, gmted/30N000E_20101117_gmted_mea075.tif`.

The fix for this is to bump `min_zoom` for GMTED down by 1 (and possibly for all other sources). (It's currently `7`.)

I'll let @iandees do the honors.

**Comment by nvkelso** [comment]
Let's verify this by running the following on all rows in the footprints database:

`update footprints set min_zoom = greater(0, min_zoom - 1)`

Once verified via an updated Lambda tiler, we should followup on https://github.com/mojodna/marblecutter/issues/12 and modify https://github.com/mojodna/marblecutter/blob/master/bin/ingest_single_footprint.sh#L48 to show:

`min_zoom=approximate_zoom - 4,`

The different content in a 256px versus 512px tile goes against the grain of what we've done for vector tiles but I see your point for raster.

**Comment by iandees** [comment]
Ran the SQL:

```
footprints=> update footprints set min_zoom = greatest(0, min_zoom - 1);
UPDATE 580635
```

**Comment by iandees** [comment]
Re-running the tile in question after the min_zoom change:

![image](https://user-images.githubusercontent.com/261584/28119464-f357a3e8-66e2-11e7-81b5-643ed8e641d6.png)

The imagery sources used: 

```gmted/30N180W_20101117_gmted_mea075.tif, gmted/30N000E_20101117_gmted_mea075.tif```

**Comment by nvkelso** [comment]
Fixed! Verified in Seth's Lambda tiler.
