### ISSUE TITLE
Bathymetry missing in New York city at zoom 15

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#42]
We had it before. It's gone now.

<img width="822" alt="screen shot 2017-07-28 at 15 10 59" src="https://user-images.githubusercontent.com/853051/28739078-a409800a-73ac-11e7-85b7-32e4b91f5cc0.png">
<img width="1120" alt="screen shot 2017-07-28 at 15 10 52" src="https://user-images.githubusercontent.com/853051/28739077-a409783a-73ac-11e7-8661-8d89f810c3e7.png">

**Comment by nvkelso** [comment]
Related to #39?

**Comment by iandees** [comment]
For example, [this tile](https://terrain-lambda.dev.mapzen.com/hillshade/15/9646/12321@2x.png) in [this area](https://terrain-lambda.dev.mapzen.com/hillshade/preview#15/40.7054/-74.0128) has sources `ned/ned19_n40x75_w074x25_nj_northeast_2007.tif, ned13/USGS_NED_13_n41w075_IMG.tif, srtm/N40W075.tif`. No etopo1 included there 🤔 .

![image](https://user-images.githubusercontent.com/261584/28758406-cc08c0c8-755c-11e7-9cdb-a7769fec171a.png)

**Comment by iandees** [comment]
Not sure what happened, but etopo1 is filling in the bathy again (from the links in my comment above this one):

![image](https://user-images.githubusercontent.com/261584/29996572-ca183224-8fc6-11e7-86c6-4ba60e9f9674.png)

**Comment by nvkelso** [comment]
Hmm. I'm still seeing a lot of null data in the water?

**Comment by iandees** [comment]
Can you give some examples?

**Comment by nvkelso** [comment]
Clarification: I see a lot of flat water where I expected some amount of variation. But you're right that there is a flat tone there now (where before it was actual null data in the water).

ETOPO1 is included in the source list:

- https://terrain-lambda.dev.mapzen.com/hillshade/15/9646/12320@2x.png

**x-imagery-sources:** `ned/ned19_n40x75_w074x25_nj_northeast_2007.tif, ned13/USGS_NED_13_n41w075_IMG.tif, srtm/N40W075.tif, etopo1/ETOPO1_Bed_g.tif`

![12320 2x](https://user-images.githubusercontent.com/853051/30000475-627bd24a-9022-11e7-9362-9819d265253e.png)

**Comment by nvkelso** [comment]
Agree this should be closed. NYC still looks funky in general but that's probably for a different issue (can't remember if we have one already or not after a week vacation ;).

**Comment by nvkelso** [comment]
The related Manhattan issue is: https://github.com/mojodna/marblecutter/issues/39.
