### ISSUE TITLE
Shelves off Golden Gate are back

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#43]
I think we fixed it last time with a priority switcheroo?

13/37.8136/-122.5019
<img width="648" alt="screen shot 2017-07-28 at 15 51 13" src="https://user-images.githubusercontent.com/853051/28739083-bbb1f3ea-73ac-11e7-9a81-adb5479f8c7d.png">

**Comment by mojodna** [comment]
Yup. `ned_topobathy > ned`. (I think `ned` got `1`.)

**Comment by iandees** [comment]
Fixed with:

```
footprints=> update footprints set priority=-1 where source='ned_topobathy';
UPDATE 35
```

![image](https://user-images.githubusercontent.com/261584/28750174-0c034348-74a8-11e7-9376-f7c0b44a235d.png)

**Comment by nvkelso** [comment]
Verified, closing :)
