### ISSUE TITLE
Additional edge blending and/or blurring to remove pixel funk between datasets

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#45]
Followup for https://github.com/mojodna/marblecutter/issues/31 for a rainy day. This issue covers adding additional blending to remove hard edges between datasets. 

That may be possible by finding the gradient over the whole image, filtering areas where it's overly steep, and applying a Gaussian filter to only that area.

**Background:**

@mojodna got dilation working in https://github.com/mojodna/marblecutter/commit/d16ec63c29d65d6976ba398cd389fd905343dc7

Before:
![dilation](https://user-images.githubusercontent.com/45/28734168-7aa75f24-7394-11e7-8af8-c4fc1300e286.png)

After:
![outliers](https://user-images.githubusercontent.com/45/28734169-7ac0ef0c-7394-11e7-9487-4d70ffc8b9ac.png)

Outlier removal turned out to be a more effective means of dealing with excessive values.

**Comment by mojodna** [comment]
[2 iterations of binary dilation are applied to masks when external masks are unavailable](https://github.com/mojodna/marblecutter/blob/e6f559ac52e7fc48a3a3fd8f298c56b54d7c01d1/marblecutter/__init__.py#L278); this improves edge behavior by removing interpolation artifacts.

**Comment by mojodna** [comment]
![iterm2 nfjqnw](https://user-images.githubusercontent.com/45/34017224-ad6f6ab6-e0d9-11e7-862b-829153919f2c.png)
