### ISSUE TITLE
Try splitting etopo1 source

### ISSUE THREAD

**Issue by iandees** [mojodna/marblecutter#51]
When using marblecutter to render pyramids with Batch, tiles that have etopo1 in them seem to render very slowly (~40 seconds a tile). One theory is that the etopo1 key on S3 gets very "hot" and slows down with hundreds of processes requesting data from that file at once. If we split the etopo1 transcoded source file into smaller pieces, it might spread that load across different keys on S3, giving us more room to render.

**Comment by nvkelso** [comment]
8x8 pieces (for 64 total files) was discussed as a good starting point.

**Comment by iandees** [comment]
Rather than split etopo into smaller pieces (which would have still given us hot S3 objects, just more of them) we set up a CloudFront distribution in front of the `elevation-sources-transcoded` bucket to act as a cache for these frequently re-used sources.

This helped a ton:
![image](https://user-images.githubusercontent.com/261584/29996540-4348cb28-8fc6-11e7-81e8-e8fd5ab2dbe1.png)

The orange line near zero is the number of GETs seen by the `elevation-sources-transcoded` bucket and the green line is the number of GETs seen by the CloudFront distribution in front of it. The cache is taking almost all the load, and the tiles are rendering way faster as a result. 👍

**Comment by nvkelso** [comment]
Rad!
