### ISSUE TITLE
Bring in 3DEP / NED bathy at zoom 11

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#6]
That's 1 zoom earlier than the current zoom 12.

Besides revealing better data earlier, this could help "paper over" some bad artifacting that happens at zoom 11 along the coast in major urban areas that also happen to have decent coastal bathy data.

- https://k6yfeg1cx6.execute-api.us-east-1.amazonaws.com/Prod/hillshade/preview#11/37.8396/-122.4849

current zoom 11
<img width="716" alt="screen shot 2017-06-23 at 13 16 11" src="https://user-images.githubusercontent.com/853051/27498931-2da776b2-5816-11e7-8df6-270cd623a558.png">

current zoom 12
<img width="798" alt="screen shot 2017-06-23 at 13 15 28" src="https://user-images.githubusercontent.com/853051/27498930-2da49d5c-5816-11e7-8585-677ae7dbb75a.png">

**Comment by nvkelso** [comment]
This should generally be all land and water 3DEP.

**Comment by nvkelso** [comment]
See ground resolution chart here – we should always be a zoom earlier than the "ground resolution" of the source.

- https://mapzen.com/documentation/terrain-tiles/data-sources/#what-is-the-ground-resolution

**Comment by nvkelso** [comment]
(So less over-zooming and more up-zooming.)

**Comment by iandees** [comment]
Currently, the `ned_topobathy` images have min_zoom of 13. I just made them 11:

```
footprints=> update footprints set min_zoom=11 where source='ned_topobathy';
UPDATE 55
```

And now zoom 11 looks like this:

![image](https://user-images.githubusercontent.com/261584/27560783-81a6649c-5a93-11e7-8693-a134683ba358.png)

Zoom 12 looks like:

![image](https://user-images.githubusercontent.com/261584/27560797-8c396594-5a93-11e7-9fa9-392fb8f04e95.png)

**Comment by nvkelso** [comment]
Verified fix, closing.
