### ISSUE TITLE
NED / 3DEP data not always included at zoom 15

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#7]
I can see NED being used at zoom 14, but looks like ETOPO is used more often than not at zoom 15 in the California test run. (I'm surprised it's not replacing with SRTM instead).

Is the footprint max_zoom wrong for NED (3DEP) and SRTM?

**zoom 15 source header:**

- `x-amz-meta-x-imagery-sources:etopo1/ETOPO1_Bed_g.tif`
- https://s3.amazonaws.com/elevation-tiles-batchdev/20170623/normal/15/5250/12550.png
- Expected NED13 (or even SRTM as fallback)

**zoom 14 source header:**

-  `x-amz-meta-x-imagery-sources:ned13/imgn39w123_13.tif`
- https://s3.amazonaws.com/elevation-tiles-batchdev/20170623/normal/14/2626/6275.png
- Correct

**Strangely NED is used around Tahoe and SF Bay Area:**

- x-amz-meta-x-imagery-sources:ned/ned19_n39x00_w120x25_ca_nv_laketahoe_2010.tif, etopo1/ETOPO1_Bed_g.tif
- https://s3.amazonaws.com/elevation-tiles-batchdev/20170623/normal/15/5443/12530.png

![pasted image at 2017_06_26 11_04 am 1](https://user-images.githubusercontent.com/853051/27553717-f0f5d0cc-5a60-11e7-9b7f-dbe3b577178b.png)

![pasted image at 2017_06_26 11_04 am](https://user-images.githubusercontent.com/853051/27553718-f0fd2e26-5a60-11e7-9144-0b9af8341063.png)

**Comment by nvkelso** [comment]
Another mixed ETOPO / NED in north bay:

- x-amz-meta-x-imagery-sources:ned_topobathy/ned19_n38x50_w122x75_ca_sanfrancisco_topobathy_2010.tif, ned/ned19_n38x50_w122x75_ca_goldengate_2010.tif, etopo1/ETOPO1_Bed_g.tif
- https://s3.amazonaws.com/elevation-tiles-batchdev/20170623/normal/15/5217/12583.png

<img width="552" alt="screen shot 2017-06-26 at 11 32 24" src="https://user-images.githubusercontent.com/853051/27554403-2a265612-5a63-11e7-942f-c992608677c2.png">

**Comment by iandees** [comment]
@nvkelso can you post links to the webmap you're screenshotting? The tiles you're linking to don't seem to display the problems you're screenshotting.

**Comment by nvkelso** [comment]
@iandees https://mapzen.com/tangram/view/?api=506/766#13.4625/37.8189/-122.4873

**Comment by nvkelso** [comment]
@iandees I retested my links above and I get the results I documented before. Hopefully the two Tangram View links above will help?

**Comment by nvkelso** [comment]
From @mojodna:

- **I’d boost NED and SRTM to 20** (as a large number).

**Background:** now that Marble Tiler short-circuits once all pixels have valid data, max zoom means a whole lot less. So generally speaking, it’s safe to boost the max zoom for sources, as Marble Tiler will attempt to use the highest-resolution data available for an area, falling back to other things that are “valid” for that zoom range.

Max zoom was originally there to prevent the number of potential sources for a tile from ballooning. And it still makes sense to keep in the software to prevent source like ETOPO from being utterly worthless at some max zooms / not cause problems when overzoomed too much.

**Comment by iandees** [comment]
I ran the following to boost the max zoom to 20 for SRTM:

```sql
update footprints set max_zoom=20 where source='srtm';
```

**Comment by nvkelso** [comment]
Most our "good" sources should have a `max_zoom` footprint review:

```
 source        | count
----------------------+-------
 etopo1               |     1
 eudem                |    72
 gmted                |   108
 mgg_greatlakes       |     3
 mgg_inundation_sandy |    56
 ned                  |  7919
 ned13                |  1262
 ned_topobathy        |    35
 nrcan_cdem           |  1021
 pgdc_5m              |  3743
 srtm                 | 14297
                      |     1
```

**Comment by iandees** [comment]
…and the same for other non-etopo1 sources:

```
footprints=> update footprints set max_zoom=20 where source='ned13';
UPDATE 10097
footprints=> update footprints set max_zoom=20 where source='ned';
UPDATE 37285
footprints=> update footprints set max_zoom=20 where source='eudem';
UPDATE 138
footprints=> update footprints set max_zoom=20 where source='ned_topobathy';
UPDATE 55
footprints=> update footprints set max_zoom=20 where source='nrcan_cdem';
UPDATE 1392
footprints=> update footprints set max_zoom=20 where source='pgdc_5m';
UPDATE 387526
```

**Comment by nvkelso** [comment]
Verified fix, closing.
