### ISSUE TITLE
Dynamic color correction

### ISSUE THREAD

**Issue by mojodna** [mojodna/marblecutter#71]
Required for raw Landsat 8 imagery, facilitates runtime changes to color profiles for individual source images - based on metadata, heuristics, + capabilities provided by [sat-utils](https://github.com/sat-utils) / [landsat-util](https://github.com/developmentseed/landsat-util) and [rio-color](https://github.com/mapbox/rio-color).

**Comment by mojodna** [comment]
Done using [`percentiles.py`](https://github.com/mojodna/marblecutter-tilezen/blob/master/bin/percentiles.py), which extracts values at 2nd, 5th, 95th, and 98th percentile for use as `{ values: { <band>: { min: <min>, max: <max> } } }`.

This implements simplistic rescaling of values to within the desired range rather than more advanced color correction.

**Comment by nvkelso** [comment]
This is working good enough to close. Followup work is probably needed, but let's open new tickets around specific problems.
