### ISSUE TITLE
oam-dynamic tiler regressions

### ISSUE THREAD

**Issue by mojodna** [mojodna/marblecutter#78]
https://d1yrsof1rvna8k.cloudfront.net/59a8dd5d23c8440011d7ad0e/0/preview#22/29.66957/-95.61510 vs. https://tiles.openaerialmap.org/59a8dd5d23c8440011d7ad0e/0/preview#22/29.66957/-95.61510

![image](https://user-images.githubusercontent.com/45/29956689-78132558-8e9d-11e7-946f-e87ddea0be74.png)

![image](https://user-images.githubusercontent.com/45/29956697-84ff3f54-8e9d-11e7-8f1d-98a94891526a.png)

https://d1yrsof1rvna8k.cloudfront.net/59a8d77c23c8440011d7ac6e/0/preview#20/30.05825/-95.42972 vs. https://tiles.openaerialmap.org/59a8d77c23c8440011d7ac6e/0/preview#20/30.05825/-95.42973

![image](https://user-images.githubusercontent.com/45/29956706-a6e80ec0-8e9d-11e7-8359-b8da46308586.png)

![image](https://user-images.githubusercontent.com/45/29956711-adfcd966-8e9d-11e7-9983-73be158e3c08.png)

**Comment by nvkelso** [comment]
SEO: Stretch

**Comment by mojodna** [comment]
The latter issue is fixed:

![image](https://user-images.githubusercontent.com/45/31227791-30f2817e-a9a9-11e7-9dd2-38be51ffc068.png)

Since the former is more of an aesthetic difference (and because the existing upscaling via `ndimage.zoom` is slow and requires large areas), I'm going to consider this fixed.
