### ISSUE TITLE
Merge tilezen branch into marblecutter-tilezen

### ISSUE THREAD

**Issue by iandees** [mojodna/marblecutter#80]
I used this branch (https://github.com/mojodna/marblecutter/compare/tilezen) to build stuff for the global terrain tiles build. Now that we're done, it needs to get merged into [marblecutter-tilezen](https://github.com/mojodna/marblecutter-tilezen/).

**Comment by nvkelso** [comment]
Some pair programming in your futures...

**Comment by mojodna** [comment]
All done. AWS-specific utilities landed in marblecutter-tilezen (the current junk drawer for this kind of deployment tooling). Custom block sizing for GeoTIFFs landed here, and support for `tar`'d (but not gzipped) ArcticDEM sources in marblecutter-tools.

**Comment by iandees** [comment]
PRs for stuff that ended up in `-tilezen`:

- https://github.com/mojodna/marblecutter-tilezen/pull/1
- https://github.com/mojodna/marblecutter-tilezen/pull/2
