### ISSUE TITLE
Blue Marble has world edge gaps

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#94]
1 pixel gap on right, and 2 px gap on bottom of world

GDAL attempting to produce square pixels when not provided a target extent, lol
Hard to get projected bounds of random CRS (coord ref system)
Should either VRT or re-project Blue Marble to solve?

**Comment by mojodna** [comment]
Fixed by using the VRT at s3://imagery-sources-tmp/blue-marble/200408.vrt, produced using: 

```bash
gdalwarp -of VRT -te -20037508.342789244 -20037508.342789255 20037508.342789244 20037508.342789244  -t_srs EPSG:3857 200408.tif 200408.vrt
```

Target extent provided per http://lists.osgeo.org/pipermail/gdal-dev/2016-August/045046.html
